### ISSUE TITLE
const enum does not work when isolatedModules is enabled

### ISSUE THREAD

**Issue by bobaaaaa** [fb55/domelementtype#16]
When using this lib (transitive via cherrio -> domhandler -> domelementtype) tsc complains with

```
error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```

when running with `--isolatedModules`. Source code:

https://github.com/fb55/domelementtype/blob/71814099d360d9ced25fadcadd44acf22d827455/src/index.ts#L38

You can find more infos about this in the popular lib chalk and how they solved this: https://github.com/chalk/chalk/issues/363

**Comment by fb55** [comment]
Hi @bobaaaaa, thanks for the report! It doesn't seem like the solution from chalk/chalk#363 applies here, as the module is already written in TypeScript. Very curious to hear other ways to solve this.

**Comment by bobaaaaa** [comment]
Personally I never use `enum`'s. I always go for [union types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#union-types) like:

```ts
type ElementType = 'root' | 'text' | 'directive' | 'comment' | 'script' | 'style' | 'tag' | 'cdata' | 'doctype';
```

But I guess this would be a breaking change :(

**Comment by AndrewLeedham** [comment]
If my understanding is correct here, it seems the export of the const enum for use in other modules is the problem. If the intent is for other modules to use said enum (which they do), it would need to be a regular enum (so the index.js file includes the enum). Or `ElementType` would need to be a union like @bobaaaaa suggested.

The former would be non-breaking as it would just add the enum to the javascript and keep the TS API the same.

**Comment by phawxby** [comment]
@fb55 do you have any suggestions on how to fix this in a non-breaking way? We're currently looking at patching this module but I prefer not to do that as it has the potential to become a maintenance burdon and should probably be fixed at the origin for everyone to benefit from.

**Comment by bobaaaaa** [comment]
Idk if it would be a breaking change when we just switch from `export const enum ElementType` to `export enum ElementType`. I just checked the generated js code. The main different is that `ElementType` is now exported as:

```js
var ElementType;
(function (ElementType) {
    /** Type for the root element of a document */
    ElementType["Root"] = "root";
    /** Type for Text */
    ElementType["Text"] = "text";
    /** Type for <? ... ?> */
    ElementType["Directive"] = "directive";
    /** Type for <!-- ... --> */
    ElementType["Comment"] = "comment";
    /** Type for <script> tags */
    ElementType["Script"] = "script";
    /** Type for <style> tags */
    ElementType["Style"] = "style";
    /** Type for Any tag */
    ElementType["Tag"] = "tag";
    /** Type for <![CDATA[ ... ]]> */
    ElementType["CDATA"] = "cdata";
    /** Type for <!doctype ...> */
    ElementType["Doctype"] = "doctype";
})(ElementType = exports.ElementType || (exports.ElementType = {}));
```

For me it looks non-breaking. I create a PR for that.
