### ISSUE TITLE
Add license key to package.json

### ISSUE THREAD

**Issue by voxpelli** [fb55/domelementtype#5]
It's currently not possible to see the license on eg. https://www.npmjs.com/package/domelementtype and tools like https://github.com/3rd-Eden/licensing have a hard time finding the information.

It would be good if you added the license type as a license key to the package.json as documented here: https://docs.npmjs.com/files/package.json#license

**Comment by voxpelli** [comment]
Same for eg. https://github.com/FB55/domutils and https://github.com/fb55/DomHandler

**Comment by fb55** [comment]
PRs welcome :)

**Comment by voxpelli** [comment]
@fb55 sent PR:s to these three projects

**Comment by fb55** [comment]
Thanks, merged all of them :)

To be precise, this isn't _exactly_ the BSD license (the word _software_ was removed), but the same terms apply nevertheless, so what the heck.
