### ISSUE TITLE
NPM package does not match this github source repository

### ISSUE THREAD

**Issue by EightArmCode** [fb55/domelementtype#8]
Could you please publish the latest version of this package to npm? The package.json contained on NPM does not list the license, and we have some in house security scripts that are programmatically inspecting for things like the presence of a license. It is in the github repo, but not in the npm package.

**Comment by honzajavorek** [comment]
Distributing the package without a license does effectively make the package to contain an unlicensed, proprietary code, which nobody can use. Fixing the issue is just one `npm publish` away though. @fb55 do you think you'd find a few minutes to fix this?

**Comment by kitfit-dave** [comment]
It seems to me that you went backwards?... 1.3.0 -> 1.2.1

**Comment by fb55** [comment]
1.3.0 was never part of this repo 🤔

Will check again, this is odd.

**Comment by potlurimanasa** [comment]
Is there an update on this? I am unable to use this package as well because of no license in package.json

**Comment by fb55** [comment]
Bumped the version.
